"use client";
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { LegacyPayrollLinks } from './legacy-payroll-links';
import { toast } from 'sonner';
const fields={pixKey:'Chave PIX oficial',nome:'Nome do beneficiário / emissor',cidade:'Cidade do beneficiário',documento:'CPF/CNPJ do emissor',endereco:'Endereço do emissor'};
export function PaymentSettings(){
 const [values,setValues]=useState<Record<string,string>>({pixKey:'',nome:'',cidade:'',documento:'',endereco:''}),[status,setStatus]=useState<any>(null),[access,setAccess]=useState(false),[saving,setSaving]=useState(false),[qr,setQr]=useState('');
 const loadStatus=()=>api.get('/comunicacao/integracoes/status').then(r=>setStatus(r.data)).catch(()=>{});
 useEffect(()=>{let mounted=true;api.get('/financeiro/configuracao-pagamentos').then(r=>{if(mounted){setValues(v=>({...v,...r.data}));setAccess(true)}}).catch(()=>{});loadStatus();return()=>{mounted=false}},[]);
 useEffect(()=>{if(!status?.whatsapp?.qrCode){setQr('');return;}api.get('/comunicacao/integracoes/qr').then(r=>setQr(r.data.qrCode || '')).catch(()=>setQr(''));},[status]);
 if(!access && !status)return null;
 return <section className="rounded-2xl border bg-card p-6 space-y-5"><h2 className="text-lg font-bold">Pagamentos e integrações</h2>{access && <form className="grid md:grid-cols-2 gap-4" onSubmit={async e=>{e.preventDefault();setSaving(true);try{await api.put('/financeiro/configuracao-pagamentos',values);toast.success('Dados institucionais salvos.');}catch(e:any){toast.error(e.response?.data?.message || 'Apenas a administração pode alterar estes dados.');}finally{setSaving(false)}}}>{Object.entries(fields).map(([key,label])=><label key={key} className="text-sm font-medium">{label}<input value={values[key] || ''} onChange={e=>setValues({...values,[key]:e.target.value})} maxLength={key==='pixKey'?77:250} required={key!=='pixKey'} className="mt-2 w-full rounded-xl border bg-background p-3"/></label>)}<p className="text-sm text-muted-foreground md:col-span-2">Cadastre os dados reais. PIX gera código para pagamento com conferência manual do financeiro; recibos exigem pagamento confirmado.</p><button disabled={saving} className="rounded-xl bg-purple-600 text-white p-3 disabled:opacity-50">{saving?'Salvando…':'Salvar dados de pagamento'}</button></form>}{access && <LegacyPayrollLinks/>}{status && <div className="space-y-3 border-t pt-4"><p>E-mail: {status.email?.configurado?'SMTP configurado':'SMTP ainda não configurado no servidor'}</p><p>WhatsApp: {status.whatsapp?.status}</p><div className="flex gap-3 flex-wrap"><button onClick={loadStatus} className="rounded-xl border px-4 py-2">Atualizar conexão</button><button className="rounded-xl border px-4 py-2" onClick={()=>api.post('/comunicacao/integracoes/verificar-email').then(()=>toast.success('Conexão SMTP validada.')).catch(e=>toast.error(e.response?.data?.message || 'Não foi possível verificar o SMTP.'))}>Verificar SMTP</button></div>{qr && <div><p className="text-sm">No WhatsApp oficial, abra Dispositivos conectados e leia este código.</p><img src={qr} width={250} height={250} alt="QR Code para conectar o WhatsApp oficial"/></div>}</div>}</section>;
}
