"use client";
import { Heart, School, Users } from "lucide-react";
import { calculateAge, formatDate } from "@/lib/utils";
interface Props { pacienteData: any; parentName: string; agenda?: any[]; evolucoes?: any[]; onOpenWhatsApp: (msg?: string) => void; }
export function PortalFamilyScreen({ pacienteData, parentName, agenda = [], evolucoes = [], onOpenWhatsApp }: Props) {
  const team = Array.from(new Map(agenda.filter(a => a.profissional).map(a => [a.profissional.id, a.profissional])).values());
  return <div className="space-y-4 pb-4"><div className="rounded-3xl bg-gradient-to-br from-purple-600 to-purple-400 p-6 text-white"><h1 className="text-xl font-bold">Espaço da família</h1><p className="mt-2">{pacienteData?.nome || "Sua criança"} · {pacienteData?.dataNascimento ? `${calculateAge(pacienteData.dataNascimento)} anos` : "Idade não informada"}</p><p className="text-sm mt-1">Responsável: {parentName}</p></div>
  <section className="rounded-2xl bg-white p-5 border border-purple-100 space-y-3"><h2 className="font-bold flex gap-2"><Users size={18}/>Equipe de atendimento</h2>{team.length ? team.map((p:any) => <div key={p.id}><p className="font-semibold">{p.usuario?.nome || "Profissional"}</p><p className="text-sm text-gray-500">{p.especialidade || p.tipo}</p></div>) : <p className="text-sm text-gray-500">A equipe aparecerá aqui após o primeiro agendamento.</p>}</section>
  <section className="rounded-2xl bg-white p-5 border border-purple-100 space-y-2"><h2 className="font-bold flex gap-2"><School size={18}/>Vida escolar</h2><p>{pacienteData?.escola || "Escola não informada"}</p><p className="text-sm text-gray-500">{pacienteData?.serie || "Série não informada"}</p></section>
  <section className="rounded-2xl bg-white p-5 border border-purple-100 space-y-3"><h2 className="font-bold flex gap-2"><Heart size={18}/>Orientações da equipe</h2>{evolucoes.filter(e => e.orientacoesPais).map(e => <article key={e.id} className="p-3 rounded-xl bg-purple-50"><p className="text-xs text-purple-600">{formatDate(e.data)} · {e.profissional?.usuario?.nome || "Equipe clínica"}</p><p className="mt-2 text-sm whitespace-pre-wrap">{e.orientacoesPais}</p></article>)}{!evolucoes.some(e=>e.orientacoesPais) && <p className="text-sm text-gray-500">Ainda não há orientações registradas.</p>}</section>
  <button onClick={()=>onOpenWhatsApp()} className="w-full bg-purple-600 text-white rounded-2xl p-3 font-semibold">Falar com o Instituto</button></div>;
}
